variable name {}
variable database_version {}
variable region {}
variable deletion_protection {}
variable project {}
variable tier {}
variable backup_configuration_enabled {}
variable backup_configuration_recovery {}
variable availability_type {}
variable ipv4_enabled {}
variable require_ssl {}
variable auth_nw_name {}
variable auth_nw_value {}