apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.gcpsmSecretEnv }}
  labels:
    type: gcpsm
type: Opaque
stringData:
  secret-access-credentials: |-
    {
      \\ https://external-secrets.io/v0.5.1/provider-google-secrets-manager/#:~:text=gcpsm%3A%0A%20%20%20%20%20%20projectID%3A%20pid-,GCP%20Service%20Account%20authentication,-You%20can%20use
    }